#! /bin/bash
#
#-------------------------------------------------------------
#
# Extracting data from a fasta file that contains
# information on chromosomes : DNA sequences and chromosome numbers
#
#-------------------------------------------------------------

# Ensuring that the file name was correctly transmitted
if [ -z "$1" ]; then exit 1; fi
cp $1 fasta_result

# Adding a new line at the end of the file to be sure that all lines are read
# This is done to counter a drawback from the command line : read
echo -e "\n" >> fasta_result

# Initializing empty variables
chromosome_seq=""
chromosome_num=""

# Reading the file and separating the data from each field in a distinct variable
while read -r line
do
	
	# ${#line} count the elements in a variable
	# ${variable:start:count} make a substring from an initial string

	first_element=${line:0:1}

	# Testing if the line is the protein accession number or a part of the amino acid sequence.
	# The symbol ">" at the beginning of a line allows the difference between each one
	if [ "$first_element" = ">" ]
	then
		# Testing if the variables are not empty to make the SQL queries and to store them in a file
		if [ -n "$chromosome_seq" -a -n "$chromosome_num" ]
		then
			if [ ! -f  fasta_sql_query_file ]
			then
				chromosome_header="##################################################################################################\n"
				chromosome_header+="#\t\t\t\tCHROMOSOME DNA SQL QUERIES\n"
				chromosome_header+="##################################################################################################\n"
				echo -e $chromosome_header > fasta_sql_query_file
			fi
	
			query_chromosome="UPDATE \`chromosome\` SET chromosome_seq='$chromosome_seq' WHERE id=$chromosome_num;"
			echo $query_chromosome >> fasta_sql_query_file
			
			chromosome_seq=""
			chromosome_num=""
		fi
		
		# Getting the chromosome number
		chromosome_num=$(echo $line | cut -d \| -f 2)
	else
		# Getting the DNA sequence
		chromosome_seq+=$line
	fi

done < fasta_result

# Testing, after the loop, if the variables are not empty to make the last SQL queries
if [ -n "$chromosome_seq" -a -n "$chromosome_num" ]
then
	if [ ! -f  fasta_sql_query_file ]
	then
		chromosome_header="##################################################################################################\n"
		chromosome_header+="#\t\t\t\tCHROMOSOME DNA SQL QUERIES\n"
		chromosome_header+="##################################################################################################\n"
		echo -e $chromosome_header > fasta_sql_query_file
	fi

	query_chromosome="UPDATE \`chromosome\` SET chromosome_seq='$chromosome_seq' WHERE id=$chromosome_num;"
	echo $query_chromosome >> fasta_sql_query_file
	
	chromosome_seq=""
	chromosome_num=""
fi

# Removing the file : fasta_result
rm -r fasta_result

exit 0


